baseURL = "http://blog.ivrpowers.com/"
languageCode = "en-us"
title = "Blog"
publishDir = "public"
theme = "hugo-theme-bleak"

[params]
  # Warning Keys are case sensitives
  Subtitle = "Streamline your business communications"
  description = "Discover all the latest about our products, technology, and Interactive Powers culture on our official blog."
  cover = "/images/cover.jpg"
  logo = "/images/logo.png"
  favicon = "/images/favicon.png"

  # Google analytics
  #googleAnalyticsUserID = "UA-xxxxxxxx-x"
  #domainVerification = "xxxxxxxxxxxxxxxxxxxxx"
  disqus = "ivrpowers"

  [params.author]
    firstName = "IVRPowers"
    lastName = "Team"
    #gender = "(fe)?male"
    #userName = "username"
    image = "/images/avatar.png"
    website = "http://www.ivrpowers.com/"
    twitter = "https://twitter.com/ivrpowers"
    github = "https://github.com/IVRPowers"
    facebook = "https://www.facebook.com/ivrpowers"
    linkedin = "https://www.linkedin.com/company/ivrpowers"
    gplus = "https://plus.google.com/110474380379482164317/"
    #gravatarHash = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
